### ISSUE TITLE
New update landed for python3.10 in jammy, PPA is no longer usable

### ISSUE THREAD

**Issue by erplsf** [deadsnakes/python3.10-jammy#1]
Greetings,
As the new updated landed here: https://launchpad.net/ubuntu/+source/python3.10/3.10.6-1~22.04.2 (security patches), I cannot use your PPA anymore to fix the bug related to venv/pre-commit installation.

**Comment by asottile** [comment]
yeah you don't really need it anymore -- you can just upgrade pre-commit / virtualenv

**Comment by asottile** [comment]
or install python3-distutils
